### ISSUE TITLE
Invalid Discover credit card number generated starting with 60111

### ISSUE THREAD

**Issue by gs202** [DavidSamir/credit-card-generator#1]
The generator returns Discover credit card numbers starting with 60111, however the official Discover documentation (IPP-VAR-Enabler-Compliance.pdf https://www.discoverglobalnetwork.com/content/dam/discover/en_us/dgn/pdfs/IPP-VAR-Enabler-Compliance.pdf) excludes them.
That documentation is directed towards “Integrated Payment Providers, Enablers and VARs” - the very people who process credit cards.

Although online validators might consider those cards as valid, those are not authoritative.
I.e creditcardvalidator.org even has a disclaimer saying they “cannot guarantee its accuracy”.

**Comment by DavidSamir** [comment]
the ticket will be udpated, 
thank you for taking the time to improve the quality of the repo
